### ISSUE TITLE
fails to minify by create-react-app

### ISSUE THREAD

**Issue by yezhiming** [Erudika/para-client-js#2]
the dependence base64-url was updated to v2.1.0, however the code is not es5 compatible, thus para-client-js could not be minified by the build script of create-react-app.

reference:
[npm run build fails to minify](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

**Comment by yezhiming** [comment]
#https://github.com/joaquimserafim/base64-url/pull/20

**Comment by albogdano** [comment]
I was able to run create-react-app and build it without errors. What is your suggested solution here?

**Comment by albogdano** [comment]
@yezhiming I've just published para-client-js `v1.28.1` which removes the `base64-url` dependency. Try it out.
